# This document is for use by readthedocs
name: eladoc
channels:
  - conda-forge
  - conda
dependencies: 
  - cartopy=0.17.0
  - rasterio=1.0.24
  - pandas=0.25.0
  - nltk=3.4.4
  - numpy=1.17.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mayavi=4.7.1
  - vtk=8.2.0
  - cython=0.29.13
  - wordcloud=1.5.0
  - pyqt=5.9.2
  - codecov=2.0.15
  - geopandas=0.5.1
  - pytest=5.0.1
  - pytest-cov=2.7.1
  - sphinx=2.1.2
  - sphinx_rtd_theme=0.4.3
  - pip
  - pip:
    #  - mayavi==4.7.1 # no need now that suitable conda pkg
    - git+https://github.com/jmp75/striplog@master#egg=striplog
    - ela
